### ISSUE TITLE
cbindgen fails when runs in tarpaulin

### ISSUE THREAD

**Issue by elichai** [eqrion/cbindgen#299]
Hi,
I'm not sure if this is a bug in tarpaulin or in cbindgen or something entirely else.
When I run `RUST_BACKTRACE=1 cargo +nightly tarpaulin -v` I get:
```
error: failed to run custom build command for `enigma-types v0.1.0 (enigma-types)`                                                                                                           
process didn't exit successfully: `enigma-types-465f750f5ad4f8f2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to generate bindings: CargoMetadata("enigma-types/Cargo.toml", Json(Error("EOF while parsing a value", line: 1, column: 0)))', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/macros.rs:16
   9: <core::result::Result<T, E>>::expect
             at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libcore/result.rs:825
  10: build_script_build::main
             at ./build.rs:11
  11: std::rt::lang_start::{{closure}}
             at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/e68bf8ae15ee6c052d0bcc9252386c5c5ee86de2/src/libstd/rt.rs:64
  16: main
  17: __libc_start_main
  18: _start

warning: build failed, waiting for other jobs to finish...
[ERROR tarpaulin] Failed to compile tests! Error: build failed
```

But when I simple run `cargo +nightly build` everything works fine.

**Comment by AxelNennker** [comment]
Works for me. I suggest to rustup update and reinstall tarpaulin.

```
ignisvulpis@namenlos:~/development/cbindgen$ cargo tarpaulin 
[INFO tarpaulin] Running Tarpaulin
[INFO tarpaulin] Building project
[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/ignisvulpis/development/cbindgen/target/debug/deps/cbindgen-dfd970e5572db1e8

running 1 test
.
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Launching test
[INFO tarpaulin] running /home/ignisvulpis/development/cbindgen/target/debug/deps/cbindgen-6b768d261fbfcb22

running 1 test
.
test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

[INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/bindgen/bindings.rs: 0/165
|| src/bindgen/bitflags.rs: 0/59
|| src/bindgen/builder.rs: 0/179
|| src/bindgen/cargo/cargo.rs: 0/99
|| src/bindgen/cargo/cargo_expand.rs: 0/51
|| src/bindgen/cargo/cargo_lock.rs: 0/9
|| src/bindgen/cargo/cargo_metadata.rs: 0/28
|| src/bindgen/cargo/cargo_toml.rs: 0/17
|| src/bindgen/cdecl.rs: 0/153
|| src/bindgen/config.rs: 0/180
|| src/bindgen/declarationtyperesolver.rs: 0/24
|| src/bindgen/dependencies.rs: 0/16
|| src/bindgen/error.rs: 0/38
|| src/bindgen/ir/annotation.rs: 0/65
|| src/bindgen/ir/cfg.rs: 0/187
|| src/bindgen/ir/constant.rs: 0/244
|| src/bindgen/ir/documentation.rs: 0/40
|| src/bindgen/ir/enumeration.rs: 0/498
|| src/bindgen/ir/function.rs: 0/122
|| src/bindgen/ir/generic_path.rs: 6/69
|| src/bindgen/ir/global.rs: 0/41
|| src/bindgen/ir/item.rs: 0/102
|| src/bindgen/ir/opaque.rs: 0/56
|| src/bindgen/ir/path.rs: 4/15
|| src/bindgen/ir/repr.rs: 0/40
|| src/bindgen/ir/structure.rs: 0/348
|| src/bindgen/ir/ty.rs: 3/426
|| src/bindgen/ir/typedef.rs: 0/93
|| src/bindgen/ir/union.rs: 0/136
|| src/bindgen/library.rs: 0/235
|| src/bindgen/mangle.rs: 53/61
|| src/bindgen/mod.rs: 0/8
|| src/bindgen/monomorph.rs: 0/49
|| src/bindgen/parser.rs: 0/465
|| src/bindgen/rename.rs: 0/147
|| src/bindgen/reserved.rs: 0/3
|| src/bindgen/utilities.rs: 0/121
|| src/bindgen/writer.rs: 0/105
|| src/logging.rs: 0/33
|| src/main.rs: 0/80
|| 
1.37% coverage, 66/4807 lines covered
ignisvulpis@namenlos:~/development/cbindgen$ 
```

**Comment by elichai** [comment]
@AxelNennker I'll try again but I meant using it on a library that uses `cbindgen` in the `build.rs`, but maybe that's the same? idk.
