### ISSUE TITLE
Different behavior depending on language selected

### ISSUE THREAD

**Issue by eliaslevy** [eqrion/cbindgen#386]
I have an FFI crate that generates a header successfully if C++ is selected as the language, but fails when C is selected.  The error is
```
thread 'main' panicked at 'Unable to mangle generic parameter ConstPtr(Path(GenericPath { path: Path { name: "str" }, export_name: "str", generics: [], ctype: None })) for 'Vec'', /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:52:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:336
   7: cbindgen::bindgen::mangle::internal_mangle_name
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:52
   8: cbindgen::bindgen::mangle::internal_mangle_name
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:37
   9: cbindgen::bindgen::mangle::internal_mangle_path
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:17
  10: cbindgen::bindgen::mangle::mangle_path
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:8
  11: cbindgen::bindgen::ir::generic_path::GenericPath::load::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/ir/opaque.rs:120
  12: cbindgen::bindgen::ir::ty::Type::specialize::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/ir/ty.rs:554
  13: cbindgen::bindgen::ir::ty::Type::specialize::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/ir/ty.rs:564
  14: cbindgen::bindgen::ir::ty::Type::specialize::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/ir/typedef.rs:108
  15: cbindgen::bindgen::library::Library::instantiate_monomorphs::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/library.rs:367
  16: cbindgen::bindgen::ir::item::ItemMap<T>::get_items::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/ir/item.rs:188
  17: cbindgen::bindgen::library::Library::instantiate_monomorphs
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/library.rs:366
  18: cbindgen::bindgen::ir::function::Function::rename_for_config::{{closure}}
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/library.rs:63
  19: <std::collections::hash::map::RandomState as core::hash::BuildHasher>::build_hasher
             at /Users/elevy/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/builder.rs:335
  20: build_script_build::main
             at some-ffi/build.rs:10
  21: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  22: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  23: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  24: std::panicking::update_count_then_panic
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  25: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  26: build_script_build::main


Process finished with exit code 101
```

It's unclear from the error message which item is causing the error.

**Comment by eliaslevy** [comment]
Setting `cpp_compat` to `true` causes it to build successfully again.

**Comment by eliaslevy** [comment]
Curious.  I can disable `cpp_compact` and change the doc style to `C`, `Cxx` or `C99` and it will build.  But if I use `Doxy`, it fails as above.

**Comment by emilio** [comment]
That's weird, do you have a repro?

**Comment by eliaslevy** [comment]
Alas, no yet.  The item causing the errors is in a dependent crate and I haven't been able to identify the item just yet.  It would be useful if the cbindgen error message included a filename and line number identifying the item.

**Comment by emilio** [comment]
Which cbindgen version is it? That callstack doesn't make sense / cannot seem to be real in trunk, as GenericPath::load doesn't do any mangling.

**Comment by eliaslevy** [comment]
Latest. 0.9.0.

**Comment by eliaslevy** [comment]
My previous comments about doc style and `cpp_compact` were wrong.  Using `Builder` API the use of `with_config` is sensitive ordering, so looks like the config was stomping on other config values configured via `with_XXX`, leading me to misdiagnose.

That said, the issue appears when targeting C but not C++.

I determined which item was at fault. It is a type alias:
```rust
pub(crate) type Fun = fn(&Event) -> Option<Vec<&str>>;
```

That causes cbindgen to die with
```
'Unable to mangle generic parameter ConstPtr(Path(GenericPath { path: Path { name: "str" }, export_name: "str", generics: [], ctype: None })) for 'Vec''
```

Reproduction is simple:
```rust
pub type Fun = fn(&str) -> Option<Vec<&str>>;
  
#[no_mangle]
pub extern fn foo(x: Fun) {
}
```

Targeting C++
```C++
WARN: Can't find str. This usually means that this type was incompatible or not found.
WARN: Can't find str. This usually means that this type was incompatible or not found.
#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <new>

template<typename T>
struct Option;

template<typename T>
struct Vec;

using Fun = Option<Vec<const str*>>(*)(const str*);

extern "C" {

void foo(Fun x);

} // extern "C"
```

Targeting C
```
thread 'main' panicked at 'Unable to mangle generic parameter ConstPtr(Path(GenericPath { path: Path { name: "str" }, export_name: "str", generics: [], ctype: None })) for 'Vec'', /Users/aleph1/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.9.0/src/bindgen/mangle.rs:52:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I should note that that type alias is not exposed to the FFI library, but that the Rust library the FFI depends on is parsed by setting `.with_parse_deps(true)` and adding the crate to the whitelist with `.with_parse_include` so that the types that are exposed to the FFI library are included in the generated header file.

**Comment by emilio** [comment]
There's no good way of doing what you want I fear. `Option` and `Vec` are not ffi-safe and the C++ code uses forward-declarations, but you cannot define a function with the `Fun` signature.

Anyhow probably we should fix the panic, thanks for the repro!

**Comment by eliaslevy** [comment]
As I mentioned the type alias is not exposed to the FFI library, but that
the Rust library the FFI depends on is parsed by setting
.with_parse_deps(true) and adding the crate to the whitelist with
.with_parse_include so that the types that are exposed to the FFI library
are included in the generated header file.

The example trying to expose Option and Vec was just for the purpose of
reproducing the panic.
