### ISSUE TITLE
panic: Result has 2 params but is being instantiated with 1 values

### ISSUE THREAD

**Issue by snyball** [eqrion/cbindgen#527]
cbdingen version: `v0.14.2`

To reproduce the error, run `cbindgen --lang c --output test.h test.rs`, with the source of `test.rs` being:
```rust
use std::fmt;

// Result<(), T> seems to trip up cbindgen, here T=fmt::Error
// as it was how I ran into it.
type FmtResult = Result<(), fmt::Error>;

fn main() {
    println!("cbindgen doesn't like Result<(), T>");
}
```
Should produce the following error+backtrace with `RUST_BACKTRACE=1`:
```
thread 'main' panicked at 'Result has 2 params but is being instantiated with 1 values', /home/sanoj/.local/share/cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.14.2/src/bindgen/ir/opaque.rs:112:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:475
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:326
  13: <cbindgen::bindgen::ir::opaque::OpaqueItem as cbindgen::bindgen::ir::item::Item>::instantiate_monomorph
  14: cbindgen::bindgen::ir::ty::Type::add_monomorphs
  15: cbindgen::bindgen::library::Library::generate
  16: cbindgen::bindgen::builder::Builder::generate
  17: cbindgen::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
```

The error does not occur with `--lang c++`.

Also reported here: https://github.com/eqrion/cbindgen/issues/206, but without a snippet to reproduce it.

**Comment by TheBlueMatt** [comment]
Heh, was just about to post a near-identical snippet to 206. CC'ing myself, mostly, but note that it doesn't have to be Result, explicitly. The following also breaks (but *not* without the `()` type parameter):

```
#[repr(C)]
pub struct CResultTempl<O, E> {
	pub result_good: bool,
	pub result: *const O,
	pub err: *const E,
}

#[no_mangle]
pub type CResultNoneAPIError = CResultTempl<(), crate::util::errors::APIError>;
#[no_mangle]
pub static CResultNoneAPIError_free: extern "C" fn(CResultNoneAPIError) = CResultTempl_free::<(), crate::util::errors::APIError>;
```

**Comment by emilio** [comment]
Yes, this is because cbindgen removes zero-sized types, and in this case gets confused.

**Comment by jackcmay** [comment]
Anyone have a workaround for this issue?

**Comment by emilio** [comment]
Depending on your code you can `cbindgen:ignore` the relevant bits.

**Comment by jackcmay** [comment]
I tried that over the offending line and it didn't work:

```rist
// cbindgen:ignore
type NoResult<(), Foo>
```

**Comment by emilio** [comment]
Needs to be a doc comment, this should work: `/// cbindgen:ignore`

(This is because `syn` ignores the other comments so we can't parse them)

**Comment by jackcmay** [comment]
I tried with doc comment too, same result.  Here is verbatim what it looks like:
```rust
/// cbindgen:ignore
type NoResult = Result<(), DigestError>;
```

**Comment by emilio** [comment]
Huh? Running:

```
cbindgen --lang c t.rs
```

With the following file:

```rust
type NoResult = Result<(), DigestError>;
```

panics, though running it on:

```rust
/// cbindgen:ignore
type NoResult = Result<(), DigestError>;
```

doesn't. So there's probably something else going on in that crate. What am I missing?

**Comment by jackcmay** [comment]
Thanks for the replies @emilio.

The offending crate is being pulled in via `PaseConfig::include` and for me, the doc comment doesn't avoid the panic.  I did see though that after a successful build (remove the `NoResult`) and adding it back that the build succeeded but only because of some kind of dep/dirty issue.  If I did a clean build the panic would show up again.  Not sure what's going on, it does seem like this should be straight forward.

For now, I've worked around it by removing the nicety `NoResult` type.

**Comment by TheBlueMatt** [comment]
This doesn't appear to be solved. eg the snippet I posted below fails on 0.16.0:

```
thread 'main' panicked at 'CResultTempl has 2 params but is being instantiated with 1 values', /home/matt/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.16.0/src/bindgen/ir/structure.rs:373:9
stack backtrace:
   0: rust_begin_unwind
             at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /usr/src/rustc-1.48.0/library/std/src/panicking.rs:437
   2: <cbindgen::bindgen::ir::structure::Struct as cbindgen::bindgen::ir::item::Item>::instantiate_monomorph
   3: cbindgen::bindgen::ir::ty::Type::add_monomorphs
   4: cbindgen::bindgen::builder::Builder::generate
   5: cbindgen::main
```

**Comment by emilio** [comment]
Hmm, yeah, that's another case we'd have to handle. It seems like the obvious thing to do in your example above is to use `void` instead of `()`, but it's not clear to me how that would work in the case the zst doesn't end up behind a pointer :/

**Comment by GoldsteinE** [comment]
This snippet also fails:

```rust
#[repr(C)]
pub enum Either<A, B> {
    Left(A),
    Right(B),
}

#[no_mangle]
extern "C" fn returns_either() -> Either<(), u8> {
    Either::Right(42)
}
```

**Comment by Millione** [comment]
Still failed with Result<(), Error>
