### ISSUE TITLE
error happend when generating 

### ISSUE THREAD

**Issue by lygstate** [eqrion/cbindgen#599]
1.3.2 version works
after upgrading to 1.5 broken.
```
  cargo:rerun-if-changed="src/header\\time\\cbindgen.toml"
  cargo:rerun-if-changed="src/header\\time\\mod.rs"

  --- stderr
  thread 'main' panicked at 'Unable to generate bindings: ParseCannotOpenFile { crate_name: "mod", src_path: "src/header\\time\\constants\\linux.rs" }', build.rs:32:10
  stack backtrace:
     0: backtrace::backtrace::trace_unsynchronized
               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace\mod.rs:66
     1: std::sys_common::backtrace::_print_fmt
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\sys_common\backtrace.rs:78
     2: std::sys_common::backtrace::_print::{{impl}}::fmt
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\sys_common\backtrace.rs:59
     3: core::fmt::write
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libcore\fmt\mod.rs:1117
     4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\io\mod.rs:1508
     5: std::sys_common::backtrace::_print
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\sys_common\backtrace.rs:62
     6: std::sys_common::backtrace::print
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\sys_common\backtrace.rs:49
     7: std::panicking::default_hook::{{closure}}
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:198
     8: std::panicking::default_hook
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:217
     9: std::panicking::rust_panic_with_hook
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:530
    10: std::panicking::begin_panic_handler
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:437
    11: core::panicking::panic_fmt
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libcore\panicking.rs:85
    12: core::option::expect_none_failed
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libcore\option.rs:1273
    13: core::result::Result<cbindgen::bindgen::bindings::Bindings, cbindgen::bindgen::error::Error>::expect<cbindgen::bindgen::bindings::Bindings,cbindgen::bindgen::error::Error>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\result.rs:963
    14: build_script_build::generate_bindings
               at .\build.rs:28
    15: build_script_build::main::{{closure}}
               at .\build.rs:53
    16: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}<std::path::PathBuf,closure-3>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:646
    17: core::iter::adapters::filter_fold::{{closure}}<std::path::PathBuf,tuple<>,closure-2,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:976
    18: core::iter::adapters::map_fold::{{closure}}<std::fs::DirEntry,std::path::PathBuf,tuple<>,closure-1,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:833
    19: core::iter::adapters::filter_fold::{{closure}}<std::fs::DirEntry,tuple<>,closure-0,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:976
    20: core::iter::adapters::filter_map_fold::{{closure}}<core::result::Result<std::fs::DirEntry, std::io::error::Error>,std::fs::DirEntry,tuple<>,fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> core::option::Option<std::fs::DirEntry>,closu
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1108
    21: core::iter::traits::iterator::Iterator::fold<std::fs::ReadDir,tuple<>,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:2003
    22: core::iter::adapters::{{impl}}::fold<std::fs::DirEntry,std::fs::ReadDir,fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> core::option::Option<std::fs::DirEntry>,tuple<>,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1156
    23: core::iter::adapters::{{impl}}::fold<core::iter::adapters::FilterMap<std::fs::ReadDir, fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> core::option::Option<std::fs::DirEntry>>,closure-0,tuple<>,closure-0>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1040
    24: core::iter::adapters::{{impl}}::fold<std::path::PathBuf,core::iter::adapters::Filter<core::iter::adapters::FilterMap<std::fs::ReadDir, fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> core::option::Option<std::fs::DirEntry>>, closure-
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:873
    25: core::iter::adapters::{{impl}}::fold<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::FilterMap<std::fs::ReadDir, fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> core::option::Option<std::fs::DirEntry>>, c
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\adapters\mod.rs:1040
    26: core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::Filter<core::iter::adapters::Map<core::iter::adapters::Filter<core::iter::adapters::FilterMap<std::fs::ReadDir, fn(core::result::Result<std::fs::DirEntry, std::io::error::Error>) -> co
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\iter\traits\iterator.rs:649
    27: build_script_build::main
               at .\build.rs:42
    28: std::rt::lang_start::{{closure}}<tuple<>>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
    29: std::rt::lang_start_internal::{{closure}}
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\rt.rs:52
    30: std::panicking::try::do_call
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:348
    31: std::panicking::try
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panicking.rs:325
    32: std::panic::catch_unwind
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\panic.rs:394
    33: std::rt::lang_start_internal
               at /rustc/6c8927b0cf80ceee19386026cf9d7fd4fd9d486f\/src\libstd\rt.rs:51
    34: std::rt::lang_start<tuple<>>
               at C:\Users\lygstate\.rustup\toolchains\nightly-2020-07-27-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libstd\rt.rs:67
    35: main
    36: invoke_main
               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    37: __scrt_common_main_seh
               at D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    38: BaseThreadInitThunk
    39: RtlUserThreadStart
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by emilio** [comment]
Do you have a test-case? It seems we're trying to open a module path that doesn't exist or something.

**Comment by lygstate** [comment]
I can reprocduce locally, that module can be sure exist.. I downgrading to 1.3.2 works

**Comment by lygstate** [comment]
I create a git repo tag for you test, is that ok?

**Comment by emilio** [comment]
Yeah, that would be fine.

**Comment by lygstate** [comment]
Here is the code, you need fetch the submodule.

https://github.com/rulibc/rulibc/commits/cbindgen

branch cbindgen

and cargo build to reproduce

**Comment by emilio** [comment]
I could repro this, I think this is the parser getting confused about `#[path]` annotations.
