### ISSUE TITLE
cbindgen panics during generation

### ISSUE THREAD

**Issue by hfiguiere** [eqrion/cbindgen#65]
cbindgen panics. This is the stack trace. I have no idea what could be the cause.

This is the current git master. But it was doing it on a previous version.

````
thread 'main' panicked at 'assertion failed: path.generics.len() == 0', /home/hub/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.1.25/src/bindgen/cdecl.rs:67:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic_new
   6: cbindgen::bindgen::cdecl::CDecl::build_type
   7: cbindgen::bindgen::bindings::Bindings::write
   8: cbindgen::main
   9: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  10: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:458
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  11: __libc_start_main
  12: _start
typedef %   
````

**Comment by hfiguiere** [comment]
Runing from the command line I get these messages:
````
ERROR: cannot use fn niepce_rust::fwk_date_to_string (path contains more than one segment)
WARN: cannot find a monomorph for GenericPath { name: "DateTime", generics: [Path(GenericPath { name: "Utc", generics: [] })] }
WARN: cannot find a monomorph for GenericPath { name: "DateTime", generics: [Path(GenericPath { name: "Utc", generics: [] })] }
WARN: cannot find a monomorph for GenericPath { name: "DateTime", generics: [Path(GenericPath { name: "Utc", generics: [] })] }
WARN: can't find QueriedContent
WARN: can't find Utc
WARN: can't find DateTime
WARN: can't find Utc
WARN: can't find DateTime
WARN: can't find Utc
WARN: can't find DateTime
WARN: can't find FileList
WARN: can't find Np
````

The repo for my project is https://github.com/hfiguiere/niepce/tree/chrono-datetime (this specific branch - just build the rust code with `cargo`)

**Comment by hfiguiere** [comment]
I suspect that it is related to `Date` being replaced by `DateTime<Utc>` (from the chrono crate)

**Comment by eqrion** [comment]
I checked out your code and was able to get it working. The problem was related to #7.

Essentially `cbindgen` used to only allow paths without multiple segments or `::`'s.

You will also need to specify that `cbindgen` should parse dependencies so that it can find `chrono::Utc`. You can do that with a `cbindgen.toml` or in your `build.rs` using `Config`.

```toml
[parse]
parse_deps = true
include = ["chrono"]
```
```rust
let mut config = Config::default();
config.parse.parse_deps = true;
config.parse.include = Some(vec!["chrono"]);
cbindgen::generate_with_config(crate_dir, config)
```
I'd like to improve `build.rs` support for these kinds of things, because it's not great.

**Comment by hfiguiere** [comment]
Thanks. That works around the problem.

**Comment by eqrion** [comment]
Thanks!
