### ISSUE TITLE
Exposed dependency structs aren't declared in generated headers

### ISSUE THREAD

**Issue by WrinklyNinja** [eqrion/cbindgen#70]
I've got some Rust like:

```rust
use libc::{size_t, uint32_t};
use esplugin::Plugin;

#[no_mangle]
pub unsafe extern "C" fn esp_plugin_count_override_records(
    plugin_ptr: *const Plugin,
    count: *mut size_t,
) -> uint32_t {
    // Do stuff
}
```

cbindgen generates a header like this from it:

```c
#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

uint32_t esp_plugin_count_override_records(const Plugin *plugin_ptr, size_t *count);
```

As you can see, there's no declaration of what `Plugin` is in the C header, so trying to compile using that fails. Adding a `struct Plugin;` to the top is enough to fix that, I use cbindgen's `header` config option to do that.

It might be relevant that the Plugin objects are only ever accessed through a pointer (it's Box'ed in Rust), I've got another library that has a similar 'handle' type that has a typedef around the Box that is used by functions as a value:

```rust
use libc::c_uint;
use dependency::RustHandle;
pub type Handle = *mut Box<RustHandle>;

#[no_mangle]
pub unsafe extern "C" fn do_something(handle: Handle) -> c_uint {
    // Do stuff
}
```

cbindgen turns that into

```c
struct Box_RustHandle;
typedef struct Box_RustHandle Box_RustHandle;
typedef Box_RwLock_Box_WritableLoadOrder *Handle;
```

which works fine.

**Comment by eqrion** [comment]
How are you using cbindgen? Are you using the `parse_deps` option?

It seems like the dependency parsing code should be able to find `esplugin::Plugin`.

**Comment by WrinklyNinja** [comment]
I've been running with `parse_deps = false`, setting it to true causes the following output:

```
> $env:RUST_BACKTRACE=1
> cargo build --all-features
   Compiling esplugin-ffi v1.0.5 (file:///C:/Users/user/esplugin/ffi)
error: failed to run custom build command for `esplugin-ffi v1.0.5 (file:///C:/Users/user/esplugin/ffi)`
process didn't exit successfully: `C:\Users\user\esplugin\target\debug\build\esplugin-ffi-c0f0b1ca7ea535b
7\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'not yet implemented', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-
0.1.27\src\bindgen\mangle.rs:40:16
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:380
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:397
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:611
   4: std::panicking::begin_panic<str*>
             at C:\projects\rust\src\libstd\panicking.rs:572
   5: cbindgen::bindgen::mangle::internal_mangle_path
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\mangle.rs:40
   6: cbindgen::bindgen::mangle::mangle_path
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\mangle.rs:8
   7: cbindgen::bindgen::ir::opaque::OpaqueItem::instantiate_monomorph
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\ir\opaque.rs:4
8
   8: cbindgen::bindgen::ir::ty::Type::add_monomorphs
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\ir\ty.rs:405
   9: cbindgen::bindgen::ir::typedef::Typedef::add_monomorphs
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\ir\typedef.rs:
66
  10: cbindgen::bindgen::library::{{impl}}::instantiate_monomorphs::{{closure}}
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\library.rs:277
  11: cbindgen::bindgen::ir::item::ItemMap<cbindgen::bindgen::ir::typedef::Typedef>::for_all_items<cbindgen::bindgen::ir::
typedef::Typedef,closure>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\ir\item.rs:175
  12: cbindgen::bindgen::library::Library::instantiate_monomorphs
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\library.rs:276
  13: cbindgen::bindgen::library::Library::generate
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\bindgen\library.rs:60
  14: cbindgen::generate_with_config<alloc::string::String*>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\lib.rs:35
  15: cbindgen::generate<alloc::string::String*>
             at C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\cbindgen-0.1.27\src\lib.rs:25
  16: build_script_build::ffi_headers::generate_headers
             at .\build.rs:16
  17: build_script_build::main
             at .\build.rs:30
  18: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:99
  19: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:54
  20: main
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  22: BaseThreadInitThunk
```

**Comment by eqrion** [comment]
That `unreachable!()` is not very helpful. What it looks like is that the code for mangling generic paths is reaching an unimplemented path.

Mangling is what automatically converts: `Vec<u32>` to `Vec_u32` for exporting to C/C++ headers. It currently cannot handle generics that contain pointers, arrays, of function pointers.

Mangling is only done for types that are used in the exported interface, do you see any types that have generics with pointers? e.g. `Vec<*const u32>` (not `* const Vec<u32>` as the pointer needs to be in the parameters.

The best workaround for this right now is to type alias the pointers away.
```rust
type U32Pointer = *const u32;
Vec<U32Pointer>
```

**Comment by WrinklyNinja** [comment]
I don't use any generics with pointers in my code (it's [this repository](https://github.com/WrinklyNinja/esplugin) if it helps), but it could be something in one of my third-party dependencies: guessing, I'd say maybe nom's macros are doing something?

If the generic pointers handling is pretty tricky, would it be possible to whitelist dependencies to parse instead, or to handle unknown types (which I'm assuming `Plugin` is if its crate isn't parsed) as opaque structs?

**Comment by WrinklyNinja** [comment]
I recently updated to cbindgen 0.4.3 and this doesn't seem to be an issue any more, thanks!
