### ISSUE TITLE
When select C language, can not generate header file 

### ISSUE THREAD

**Issue by yyjia** [eqrion/cbindgen#772]
when use C++ languge , it work well. but can not generate header, when select C language

```
revm git:(gorust) ✗ rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.63.0-nightly (c3b7d7b49 2022-06-17)`
➜  revm git:(gorust) ✗ rustc -V
rustc 1.63.0-nightly (c3b7d7b49 2022-06-17)
➜  revm git:(gorust) ✗ RUST_BACKTRACE=1 cbindgen --crate revm --output librust.h --lang c
WARN: Skip revm::__DARWIN_SUF_64_BIT_INO_T - (Unsupported literal expression. ByteStr(LitByteStr { token: b"$INODE64\0" }))
WARN: Skip revm::__DARWIN_SUF_1050 - (Unsupported literal expression. ByteStr(LitByteStr { token: b"$1050\0" }))
WARN: Skip revm::__DARWIN_SUF_EXTSN - (Unsupported literal expression. ByteStr(LitByteStr { token: b"$DARWIN_EXTSN\0" }))
WARN: Skip revm::P_tmpdir - (Unsupported literal expression. ByteStr(LitByteStr { token: b"/var/tmp/\0" }))
thread 'main' panicked at 'not implemented: Unable to mangle generic parameter Array(Primitive(Integer { zeroable: true, signed: false, kind: B8 }), Value("4")) for '__BindgenBitfieldUnit'', /Users/mac/.cargo/registry/src/github.com-1ecc6299db9ec823/cbindgen-0.24.3/src/bindgen/mangle.rs:132:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: cbindgen::bindgen::mangle::Mangler::append_mangled_type
   3: cbindgen::bindgen::mangle::Mangler::mangle
   4: cbindgen::bindgen::ir::structure::Struct::specialize
   5: <cbindgen::bindgen::ir::structure::Struct as cbindgen::bindgen::ir::item::Item>::instantiate_monomorph
   6: cbindgen::bindgen::ir::ty::Type::add_monomorphs
   7: cbindgen::bindgen::library::Library::generate
   8: cbindgen::bindgen::builder::Builder::generate
   9: cbindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
➜  revm git:(gorust) ✗ cbindgen -V
cbindgen 0.24.3
```

**Comment by dariusc93** [comment]
It could be that trying to generate a header for something that isnt FFI safe. Might be a similar to https://github.com/eqrion/cbindgen/issues/386. Do you have any code you could share?

**Comment by yyjia** [comment]
> It could be that trying to generate a header for something that isnt FFI safe. Might be a similar to #386. Do you have any code you could share?

I re-organized my code and found that there is a ffi-safe problem somewhere. After I remove this block, the c header can be generated normally。thx @dariusc93 
```rust
pub type max_align_t = u128;

extern "C" {
    pub fn strtold(
        arg1: *const ::std::os::raw::c_char,
        arg2: *mut *mut ::std::os::raw::c_char,
    ) -> u128;
}
```
